@startuml Aktivitaetendiagramm_Bezahlvorgang
title Aktivitaetsdiagramm - Bezahlvorgang

start

:Autofahrer naehert sich dem Kassenautomaten;

:Ticket in den Automaten einfuehren;

if (Ist das Ticket gueltig?) then (ja)
    :System berechnet Parkgebuehren;
    :Betrag auf Display anzeigen;

    if (Welche Zahlungsart?) then (Bar)
        :Automat fordert Bargeld ein;
        :Autofahrer wirft Geld ein;
        :Quittung drucken;
    else (Kreditkarte)
        :Automat fordert Kreditkarte ein;
        :Autofahrer steckt Kreditkarte ein;
        :Quittung drucken;
    endif

    :Ticket freigeben;
    :Schranke oeffnen;

else (nein)
    :Fehlermeldung anzeigen;
endif

stop

@enduml
