@startuml USE_CASE_Diagramm
title Use Case Diagramm - Parkhausverwaltung

actor "Driver" as driver
actor "Manager" as manager

usecase "Create Parking" as UC1
usecase "Enter Parking" as UC2
usecase "Exit Parking" as UC3

driver --> UC2
driver --> UC3
manager --> UC1

UC2 --> UC3 : <<include>>

@enduml
